netinet/sctp_usrreq.c: fix `gcc-16` build error (#729)
Upcoming `gcc-16` improved unused variable use detection and now
reports unused` cnt` as:

    usrsctplib/netinet/sctp_usrreq.c: In function 'sctp_setopt':
    usrsctplib/netinet/sctp_usrreq.c:5571:29: error: variable 'cnt' set but not used [-Werror=unused-but-set-variable=]
     5571 |                         int cnt;
          |                             ^~~

The change drops unused `cnt` variable.